services:
  web:
    build: .
    container_name: ci3_shop_web
    ports:
      - "8086:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "apache2-foreground"

  db:
    image: mysql:8.0
    container_name: ci3_shop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci3_shop
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci3_shop_phpmyadmin
    restart: always
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
